fix(ci): downgrade to `ubuntu-24.04` on `bake-image` workflow
Ths is needed because the `Chizkiyahu/delete-untagged-ghcr-action@v6` action
fails on `ubuntu-26.04` with the following error:

> Error: The version '3.11' with architecture 'x64' was not found for Ubuntu 26.04.

Signed-off-by: roib20 <66280613+roib20@users.noreply.github.com>